[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = true
enableXsrfProtection = false
maxUploadSize = 500
maxMessageSize = 500
fileUploaderEnabled = true

[browser]
gatherUsageStats = false

